### ISSUE TITLE
why get the 404 error need login?

### ISSUE THREAD

**Issue by misakar** [miguelgrinberg/api-pycon2015#5]
![2016-06-16 12 41 18](https://cloud.githubusercontent.com/assets/10671733/16088785/43d10010-335b-11e6-97f3-918fef2afb99.png)

**Comment by miguelgrinberg** [comment]
Just an oversight. The login_required decorator doesn't do anything in this function.

**Comment by misakar** [comment]
![2016-06-16 1 32 37](https://cloud.githubusercontent.com/assets/10671733/16090611/cc89d4f2-3362-11e6-9957-3d78075b7ff4.png)
Here I get wrong url , return 404 error maybe better.

**Comment by miguelgrinberg** [comment]
You could say that it is better to report 401 and not give away the information of what endpoints are or are not available.

**Comment by misakar** [comment]
@miguelgrinberg I know, Thanks 👍
